# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cqk0O4v4n3ftrt2bNz7DmkwBKYTN_5Qq
"""

#to make colab work with the local Google drive version

from google.colab import drive
drive.mount('/content/gdrive')

#writing the ET part of ETL
import os
import re

#defying the location of the files to read from and to write into
frp="/content/gdrive/My Drive/Experiments/testassignments/quantori/CoordStatusMA.csv"
fwp="/content/gdrive/My Drive/Experiments/testassignments/quantori/new_CoordStatusMA.csv"

fr = open(frp, "r")
fw = open(fwp, "a")
fw.writelines("status,date_timestamp,latitude,longitude,number_of_people"+"\n")

for line in fr:
  if len(line.replace("Status",""))<len(line):
    status=line.replace(" ","")[7:len(m)]
  else:
    print((len(line.split(","))-1)/3)
    linearray=re.split("(-?\d{2}\.\d{3},{1}-?\d{2}\.\d{3},[0-9]*)",line)
    status_month=status+","+linearray[0].replace(",","")
    #print(status_month)
    for el in linearray:
      if el.count(",")==2:
        #print(status_month+","+el)
        fw.writelines(status_month+","+el+"\n")

fw.close()
fr.close()
